version: '3.7'
services:
  be:
    build: 
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - mynetwork

networks:
  mynetwork:

