version: '3.7'
services:
  be:
    build: 
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork
      
  foodapp:
    build: 
      context: ./FoodApp
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - mynetwork

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - mynetwork

networks:
  mynetwork:

